### ISSUE TITLE
Need to run the python setup.py inside the sample app dir

### ISSUE THREAD

**Issue by natea** [Pylons/pyramid_jqm#1]
The docs tell you to run python setup.py develop after you check out the code from github, but after you create the sample app, the docs are missing the step to run python setup.py develop in that directory.

If you don't do this you get this error:

```
# bin/paster serve pyjqm/development.ini
Traceback (most recent call last):
  File "bin/paster", line 8, in <module>
    load_entry_point('PasteScript==1.7.4.2', 'console_scripts', 'paster')()
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/command.py", line 238, in run
    result = self.command()
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteScript-1.7.4.2-py2.6.egg/paste/script/serve.py", line 321, in loadapp
    **kw)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 450, in get_context
    global_additions=global_additions)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 559, in _pipeline_app_context
    APP, pipeline[-1], global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/PasteDeploy-1.5.0-py2.6.egg/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/nateaune/code/pyramid_jqm/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pyjqm
```

**Comment by tseaver** [comment]
Thanks for the report.  I have checked in changes to address it, which should show up soon on docs.pylonsproject.org.

**Comment by natea** [comment]
Great, thanks for this awesome example app Tres! Excited about the possibilities of building lightweight mobile apps with jQuery Mobile and Pyramid.
