### ISSUE TITLE
Tutorial doesn't work

### ISSUE THREAD

**Issue by ghost** [Pylons/pyramid_jqm#6]
http://docs.pylonsproject.org/projects/pyramid_jqm/en/latest/

following those steps (on linux) $ pserve development.ini doesn't works

but pyramid starter/alchemy scaffolds works very well.

[fcortesi@localhost MyApp]$ ../jqmEnv/bin/pserve development.ini
Traceback (most recent call last):
  File "../jqmEnv/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.5a2', 'console_scripts', 'pserve')()
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/pkg_resources.py", line 2260, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/pyramid-1.5a2-py3.3.egg/pyramid/scripts/pserve.py", line 31, in <module>
    from pyramid.paster import setup_logging
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/pyramid-1.5a2-py3.3.egg/pyramid/paster.py", line 10, in <module>
    from pyramid.scripting import prepare
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/pyramid-1.5a2-py3.3.egg/pyramid/scripting.py", line 1, in <module>
    from pyramid.config import global_registries
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/pyramid-1.5a2-py3.3.egg/pyramid/config/**init**.py", line 9, in <module>
    from webob.exc import WSGIHTTPException as WebobWSGIHTTPException
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/WebOb-1.2.3-py3.3.egg/webob/exc.py", line 1115, in <module>
    from paste import httpexceptions
  File "/home/fcortesi/Test/Frameworks/Pyramid/jqmEnv/lib/python3.3/site-packages/Paste-1.7.5.1-py3.3.egg/paste/httpexceptions.py", line 634
    except HTTPException, exc:
                        ^
SyntaxError: invalid syntax
[fcortesi@localhost MyApp]$

**Comment by mcdonc** [comment]
Not compat w py3
